#!/usr/bin/env python3
"""
Case Duration Relationship Handler for Legal Judgment Database

This module handles the creation of case duration nodes and their relationships with judgments.

Author: Anish
Date: November 2025
"""

import sys
from pathlib import Path
from typing import List, Dict, Tuple

# Add parent directory to path for imports
sys.path.append(str(Path(__file__).parent.parent))

from models import JudgmentData
from utils import setup_logging, sanitize_string, parse_list_data, create_node_id, format_rdf_triple


class CaseDurationRelationshipHandler:
    """
    Handles case duration nodes and relationships for RDF generation.
    """
    
    def __init__(self):
        """Initialize the Case Duration Relationship Handler."""
        self.logger = setup_logging()
        self.rdf_lines: List[str] = []
        self.case_duration_map: Dict[str, str] = {}
        self.case_duration_counter: int = 1
        self.stats = {
            'total_case_durations': 0,
            'case_duration_relationships': 0,
            'total_triples': 0
        }
        
        self.logger.info("📅 Case Duration Relationship Handler initialized")
    
    def create_case_duration_relationship(self, judgment: JudgmentData) -> List[str]:
        """
        Create case duration node and relationship for a single judgment.
        
        Args:
            judgment: JudgmentData object containing judgment information
            
        Returns:
            List[str]: RDF triples for case duration relationship
        """
        relationship_triples = []
        
        if not judgment.case_duration or judgment.case_duration.lower() in ['nan', '', 'null']:
            self.logger.debug(f"⚠️ No case duration data for judgment: {judgment.title[:50]}...")
            return relationship_triples
        
        duration_clean = sanitize_string(judgment.case_duration)
        if not duration_clean:
            return relationship_triples
        
        self.logger.info(f"🔄 Processing case duration '{duration_clean}' for: {judgment.title[:50]}...")
        
        # Get or create case duration node
        duration_node = self._get_or_create_case_duration_node(duration_clean)
        
        # Create relationship
        relationship_triple = format_rdf_triple(judgment.judgment_node, 'has_case_duration', duration_node, False)
        relationship_triples.append(relationship_triple)
        self.stats['case_duration_relationships'] += 1
        
        self.logger.info(f"✓ Created case duration relationship: {judgment.judgment_node} -> {duration_node}")
        
        return relationship_triples
    
    def _get_or_create_case_duration_node(self, duration_info: str) -> str:
        """
        Get existing case duration node or create a new one.
        
        Args:
            duration_info: Duration information (e.g., "2019-03-15 to 2019-11-18")
            
        Returns:
            str: Case duration node identifier
        """
        if duration_info in self.case_duration_map:
            return self.case_duration_map[duration_info]
        
        # Create new case duration node
        duration_node = create_node_id('case_duration', self.case_duration_counter)
        self.case_duration_map[duration_info] = duration_node
        self.case_duration_counter += 1
        
        # Add case duration node properties
        duration_triples = [
            format_rdf_triple(duration_node, 'dgraph.type', 'CaseDuration'),
            format_rdf_triple(duration_node, 'case_duration_id', duration_node),
            format_rdf_triple(duration_node, 'duration', duration_info)
        ]
        
        self.rdf_lines.extend(duration_triples)
        self.stats['total_case_durations'] += 1
        
        self.logger.info(f"📄 Created case duration node: {duration_node} for '{duration_info}'")
        return duration_node
    
    def get_all_rdf_triples(self) -> List[str]:
        """
        Get all RDF triples generated by this handler.
        
        Returns:
            List[str]: All RDF triples
        """
        return self.rdf_lines
    
    def get_statistics(self) -> Dict[str, int]:
        """
        Get processing statistics.
        
        Returns:
            Dict[str, int]: Statistics dictionary
        """
        self.stats['total_triples'] = len(self.rdf_lines)
        return self.stats.copy()
    
    def reset(self) -> None:
        """Reset the handler for a new processing session."""
        self.rdf_lines.clear()
        self.case_duration_map.clear()
        self.case_duration_counter = 1
        self.stats = {
            'total_case_durations': 0,
            'case_duration_relationships': 0,
            'total_triples': 0
        }
        self.logger.info("🔄 Case Duration Relationship Handler reset")


def debug_case_duration_relationships(judgments: List[JudgmentData]) -> None:
    """
    Debug function to test case duration relationships independently.
    
    Args:
        judgments: List of JudgmentData objects
    """
    print("🐛 DEBUG: Testing Case Duration Relationships")
    print("=" * 50)
    
    handler = CaseDurationRelationshipHandler()
    all_relationship_triples = []
    
    for judgment in judgments:
        print(f"\n🔄 Processing: {judgment.title[:50]}...")
        print(f"   Duration: {judgment.case_duration}")
        relationship_triples = handler.create_case_duration_relationship(judgment)
        all_relationship_triples.extend(relationship_triples)
    
    # Get all triples
    all_triples = handler.get_all_rdf_triples() + all_relationship_triples
    stats = handler.get_statistics()
    
    # Print results
    print(f"\n📊 Results:")
    print(f"   • Total case durations created: {stats['total_case_durations']}")
    print(f"   • Total case duration relationships: {stats['case_duration_relationships']}")
    print(f"   • Total RDF triples: {len(all_triples)}")
    
    print(f"\n📝 Sample triples:")
    for i, triple in enumerate(all_triples[:5]):
        print(f"   {i+1}. {triple}")
    
    if len(all_triples) > 5:
        print(f"   ... and {len(all_triples) - 5} more triples")
    
    return all_triples


if __name__ == "__main__":
    # Test with sample data
    sample_judgments = [
        JudgmentData(
            idx=0,
            title="Sample Judgment 1",
            judgment_node="<j1>",
            case_duration="2019-03-15 to 2019-11-18"
        ),
        JudgmentData(
            idx=1,
            title="Sample Judgment 2",
            judgment_node="<j2>",
            case_duration="2020-07-22 to 2021-08-18"
        ),
        JudgmentData(
            idx=2,
            title="Sample Judgment 3",
            judgment_node="<j3>",
            case_duration="2019-03-15 to 2019-11-18"  # Same duration as judgment 1
        )
    ]
    
    debug_case_duration_relationships(sample_judgments)
