#!/usr/bin/env python3
"""
Judge Relationship Handler for Legal Judgment Database

This module handles the creation of judge nodes and their relationships with judgments.
It can be used independently for debugging or as part of the main RDF generator.

Author: Anish
Date: November 2025
"""

import sys
from pathlib import Path
from typing import List, Dict, Tuple

# Add parent directory to path for imports
sys.path.append(str(Path(__file__).parent.parent))

from models import JudgmentData
from utils import setup_logging, sanitize_string, parse_list_data, create_node_id, format_rdf_triple


class JudgeRelationshipHandler:
    """
    Handles judge nodes and relationships for RDF generation.
    """
    
    def __init__(self):
        """Initialize the Judge Relationship Handler."""
        self.logger = setup_logging()
        self.rdf_lines: List[str] = []
        self.judge_map: Dict[str, str] = {}  # Maps judge_name -> stable judge_node_id
        self.stats = {
            'total_judges': 0,
            'judge_relationships': 0,
            'total_triples': 0
        }
        
        self.logger.info("📋 Judge Relationship Handler initialized")
    
    def create_judge_relationships(self, judgment: JudgmentData) -> List[str]:
        """
        Create judge nodes and relationships for a single judgment.
        
        Args:
            judgment: JudgmentData object containing judgment information
            
        Returns:
            List[str]: RDF triples for judge relationships
        """
        relationship_triples = []
        judges = parse_list_data(judgment.judge_name)
        
        self.logger.info(f"🔄 Processing {len(judges)} judges for judgment: {judgment.title[:50]}...")
        
        for judge_name in judges:
            judge_clean = sanitize_string(judge_name)
            if not judge_clean:
                continue
            
            # Get or create judge node
            judge_node = self._get_or_create_judge_node(judge_clean)
            
            # Create relationship
            relationship_triple = format_rdf_triple(judgment.judgment_node, 'judged_by', judge_node, False)
            relationship_triples.append(relationship_triple)
            self.stats['judge_relationships'] += 1
            
            self.logger.info(f"✓ Created judge relationship: {judgment.judgment_node} -> {judge_node}")
        
        return relationship_triples
    
    def _get_or_create_judge_node(self, judge_name: str) -> str:
        """
        Get existing judge node or create a new one using stable content-based ID.
        
        Args:
            judge_name: Name of the judge
            
        Returns:
            str: Judge node identifier (stable across batches)
        """
        if judge_name in self.judge_map:
            return self.judge_map[judge_name]
        
        # Create stable judge node ID based on judge name
        # This ensures same judge always gets same ID across different batches
        judge_node = create_node_id('judge', unique_key=judge_name)
        self.judge_map[judge_name] = judge_node
        
        # Add judge node properties
        judge_triples = [
            format_rdf_triple(judge_node, 'dgraph.type', 'Judge'),
            format_rdf_triple(judge_node, 'judge_id', judge_node),
            format_rdf_triple(judge_node, 'name', judge_name)
        ]
        
        self.rdf_lines.extend(judge_triples)
        self.stats['total_judges'] += 1
        
        self.logger.info(f"📄 Created judge node: {judge_node} for '{judge_name}'")
        return judge_node
    
    def get_all_rdf_triples(self) -> List[str]:
        """
        Get all RDF triples generated by this handler.
        
        Returns:
            List[str]: All RDF triples
        """
        return self.rdf_lines
    
    def get_statistics(self) -> Dict[str, int]:
        """
        Get processing statistics.
        
        Returns:
            Dict[str, int]: Statistics dictionary
        """
        self.stats['total_triples'] = len(self.rdf_lines)
        return self.stats.copy()
    
    def reset(self) -> None:
        """Reset the handler for a new processing session."""
        self.rdf_lines.clear()
        self.judge_map.clear()
        self.judge_counter = 1
        self.stats = {
            'total_judges': 0,
            'judge_relationships': 0,
            'total_triples': 0
        }
        self.logger.info("🔄 Judge Relationship Handler reset")


def debug_judge_relationships(judgments: List[JudgmentData]) -> None:
    """
    Debug function to test judge relationships independently.
    
    Args:
        judgments: List of JudgmentData objects
    """
    print("🐛 DEBUG: Testing Judge Relationships")
    print("=" * 50)
    
    handler = JudgeRelationshipHandler()
    all_relationship_triples = []
    
    for judgment in judgments:
        print(f"\n🔄 Processing: {judgment.title[:50]}...")
        relationship_triples = handler.create_judge_relationships(judgment)
        all_relationship_triples.extend(relationship_triples)
    
    # Get all triples
    all_triples = handler.get_all_rdf_triples() + all_relationship_triples
    stats = handler.get_statistics()
    
    # Print results
    print(f"\n📊 Results:")
    print(f"   • Total judges created: {stats['total_judges']}")
    print(f"   • Total judge relationships: {stats['judge_relationships']}")
    print(f"   • Total RDF triples: {len(all_triples)}")
    
    print(f"\n📝 Sample triples:")
    for i, triple in enumerate(all_triples[:5]):
        print(f"   {i+1}. {triple}")
    
    if len(all_triples) > 5:
        print(f"   ... and {len(all_triples) - 5} more triples")
    
    return all_triples


if __name__ == "__main__":
    # Test with sample data
    sample_judgments = [
        JudgmentData(
            idx=0,
            title="Sample Judgment 1",
            judgment_node="<j1>",
            judge_name='["Justice A. B. Smith", "Justice C. D. Jones"]'
        ),
        JudgmentData(
            idx=1,
            title="Sample Judgment 2", 
            judgment_node="<j2>",
            judge_name='["Justice A. B. Smith", "Justice E. F. Wilson"]'
        )
    ]
    
    debug_judge_relationships(sample_judgments)
