#!/usr/bin/env python3
"""
Outcome Relationship Handler for Legal Judgment Database

This module handles the creation of outcome nodes and their relationships with judgments.

Author: Anish
Date: November 2025
"""

import sys
from pathlib import Path
from typing import List, Dict, Tuple

# Add parent directory to path for imports
sys.path.append(str(Path(__file__).parent.parent))

from models import JudgmentData
from utils import setup_logging, sanitize_string, parse_list_data, create_node_id, format_rdf_triple


class OutcomeRelationshipHandler:
    """
    Handles outcome nodes and relationships for RDF generation.
    """
    
    def __init__(self):
        """Initialize the Outcome Relationship Handler."""
        self.logger = setup_logging()
        self.rdf_lines: List[str] = []
        self.outcome_map: Dict[str, str] = {}
        self.outcome_counter: int = 1
        self.stats = {
            'total_outcomes': 0,
            'outcome_relationships': 0,
            'total_triples': 0
        }
        
        self.logger.info("⚖️ Outcome Relationship Handler initialized")
    
    def create_outcome_relationship(self, judgment: JudgmentData) -> List[str]:
        """
        Create outcome node and relationship for a single judgment.
        
        Args:
            judgment: JudgmentData object containing judgment information
            
        Returns:
            List[str]: RDF triples for outcome relationship
        """
        relationship_triples = []
        
        if not judgment.outcome or judgment.outcome.lower() in ['nan', '', 'null']:
            self.logger.debug(f"⚠️ No outcome data for judgment: {judgment.title[:50]}...")
            return relationship_triples
        
        outcome_clean = sanitize_string(judgment.outcome)
        if not outcome_clean:
            return relationship_triples
        
        self.logger.info(f"🔄 Processing outcome '{outcome_clean}' for: {judgment.title[:50]}...")
        
        # Get or create outcome node
        outcome_node = self._get_or_create_outcome_node(outcome_clean)
        
        # Create relationship
        relationship_triple = format_rdf_triple(judgment.judgment_node, 'has_outcome', outcome_node, False)
        relationship_triples.append(relationship_triple)
        self.stats['outcome_relationships'] += 1
        
        self.logger.info(f"✓ Created outcome relationship: {judgment.judgment_node} -> {outcome_node}")
        
        return relationship_triples
    
    def _get_or_create_outcome_node(self, outcome_name: str) -> str:
        """
        Get existing outcome node or create a new one.
        
        Args:
            outcome_name: Name/description of the outcome
            
        Returns:
            str: Outcome node identifier
        """
        if outcome_name in self.outcome_map:
            return self.outcome_map[outcome_name]
        
        # Create new outcome node
        outcome_node = create_node_id('outcome', self.outcome_counter)
        self.outcome_map[outcome_name] = outcome_node
        self.outcome_counter += 1
        
        # Add outcome node properties
        outcome_triples = [
            format_rdf_triple(outcome_node, 'dgraph.type', 'Outcome'),
            format_rdf_triple(outcome_node, 'outcome_id', outcome_node),
            format_rdf_triple(outcome_node, 'name', outcome_name)
        ]
        
        self.rdf_lines.extend(outcome_triples)
        self.stats['total_outcomes'] += 1
        
        self.logger.info(f"📄 Created outcome node: {outcome_node} for '{outcome_name}'")
        return outcome_node
    
    def get_all_rdf_triples(self) -> List[str]:
        """
        Get all RDF triples generated by this handler.
        
        Returns:
            List[str]: All RDF triples
        """
        return self.rdf_lines
    
    def get_statistics(self) -> Dict[str, int]:
        """
        Get processing statistics.
        
        Returns:
            Dict[str, int]: Statistics dictionary
        """
        self.stats['total_triples'] = len(self.rdf_lines)
        return self.stats.copy()
    
    def reset(self) -> None:
        """Reset the handler for a new processing session."""
        self.rdf_lines.clear()
        self.outcome_map.clear()
        self.outcome_counter = 1
        self.stats = {
            'total_outcomes': 0,
            'outcome_relationships': 0,
            'total_triples': 0
        }
        self.logger.info("🔄 Outcome Relationship Handler reset")


def debug_outcome_relationships(judgments: List[JudgmentData]) -> None:
    """
    Debug function to test outcome relationships independently.
    
    Args:
        judgments: List of JudgmentData objects
    """
    print("🐛 DEBUG: Testing Outcome Relationships")
    print("=" * 50)
    
    handler = OutcomeRelationshipHandler()
    all_relationship_triples = []
    
    for judgment in judgments:
        print(f"\n🔄 Processing: {judgment.title[:50]}...")
        print(f"   Outcome: {judgment.outcome}")
        relationship_triples = handler.create_outcome_relationship(judgment)
        all_relationship_triples.extend(relationship_triples)
    
    # Get all triples
    all_triples = handler.get_all_rdf_triples() + all_relationship_triples
    stats = handler.get_statistics()
    
    # Print results
    print(f"\n📊 Results:")
    print(f"   • Total outcomes created: {stats['total_outcomes']}")
    print(f"   • Total outcome relationships: {stats['outcome_relationships']}")
    print(f"   • Total RDF triples: {len(all_triples)}")
    
    print(f"\n📝 Sample triples:")
    for i, triple in enumerate(all_triples[:5]):
        print(f"   {i+1}. {triple}")
    
    if len(all_triples) > 5:
        print(f"   ... and {len(all_triples) - 5} more triples")
    
    return all_triples


if __name__ == "__main__":
    # Test with sample data
    sample_judgments = [
        JudgmentData(
            idx=0,
            title="Sample Judgment 1",
            judgment_node="<j1>",
            outcome="Petitioner Won"
        ),
        JudgmentData(
            idx=1,
            title="Sample Judgment 2",
            judgment_node="<j2>",
            outcome="Respondent Won"
        ),
        JudgmentData(
            idx=2,
            title="Sample Judgment 3",
            judgment_node="<j3>",
            outcome="Petitioner Won"  # Same outcome as judgment 1
        )
    ]
    
    debug_outcome_relationships(sample_judgments)
